blank_issues_enabled: false
contact_links:
  - name: Abhinas support
    url: https://t.me/DOSTI_GROUP_1234
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://t.me/abhinasroy
    about: Basic documentation for setting up.
